"""initial migration

Revision ID: 3b78aede5257
Revises: 
Create Date: 2023-03-17 10:17:16.477117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b78aede5257'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passwordhash', sa.Text(), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.TEXT(), nullable=False))
        batch_op.drop_column('passwordhash')

    # ### end Alembic commands ###
