"""initial migration

Revision ID: 9d4cf7441f6e
Revises: 3b78aede5257
Create Date: 2023-03-17 10:19:05.724359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d4cf7441f6e'
down_revision = '3b78aede5257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.Text(), nullable=False))
        batch_op.drop_column('passwordhash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passwordhash', sa.TEXT(), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
